// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=itest
//

// Package itest is a generated GoMock package.
package itest

import (
	context "context"
	reflect "reflect"

	probe "github.com/n-r-w/itestkit/queue/probe"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboundHarness is a mock of OutboundHarness interface.
type MockOutboundHarness struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundHarnessMockRecorder
	isgomock struct{}
}

// MockOutboundHarnessMockRecorder is the mock recorder for MockOutboundHarness.
type MockOutboundHarnessMockRecorder struct {
	mock *MockOutboundHarness
}

// NewMockOutboundHarness creates a new mock instance.
func NewMockOutboundHarness(ctrl *gomock.Controller) *MockOutboundHarness {
	mock := &MockOutboundHarness{ctrl: ctrl}
	mock.recorder = &MockOutboundHarnessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundHarness) EXPECT() *MockOutboundHarnessMockRecorder {
	return m.recorder
}

// AwaitOutbound mocks base method.
func (m *MockOutboundHarness) AwaitOutbound(ctx context.Context) (probe.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AwaitOutbound", ctx)
	ret0, _ := ret[0].(probe.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AwaitOutbound indicates an expected call of AwaitOutbound.
func (mr *MockOutboundHarnessMockRecorder) AwaitOutbound(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AwaitOutbound", reflect.TypeOf((*MockOutboundHarness)(nil).AwaitOutbound), ctx)
}

// CleanupBroker mocks base method.
func (m *MockOutboundHarness) CleanupBroker(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupBroker", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupBroker indicates an expected call of CleanupBroker.
func (mr *MockOutboundHarnessMockRecorder) CleanupBroker(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupBroker", reflect.TypeOf((*MockOutboundHarness)(nil).CleanupBroker), ctx)
}

// PlanOutbound mocks base method.
func (m *MockOutboundHarness) PlanOutbound(ctx context.Context, expectation probe.OutboundExpectation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlanOutbound", ctx, expectation)
	ret0, _ := ret[0].(error)
	return ret0
}

// PlanOutbound indicates an expected call of PlanOutbound.
func (mr *MockOutboundHarnessMockRecorder) PlanOutbound(ctx, expectation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlanOutbound", reflect.TypeOf((*MockOutboundHarness)(nil).PlanOutbound), ctx, expectation)
}

// VerifyOutbound mocks base method.
func (m *MockOutboundHarness) VerifyOutbound(ctx context.Context) (probe.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOutbound", ctx)
	ret0, _ := ret[0].(probe.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyOutbound indicates an expected call of VerifyOutbound.
func (mr *MockOutboundHarnessMockRecorder) VerifyOutbound(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOutbound", reflect.TypeOf((*MockOutboundHarness)(nil).VerifyOutbound), ctx)
}
