// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=itestkit
//

// Package itestkit is a generated GoMock package.
package itestkit

import (
	context "context"
	json "encoding/json"
	fs "io/fs"
	reflect "reflect"
	testing "testing"

	gomock "go.uber.org/mock/gomock"
)

// MockCaseSource is a mock of CaseSource interface.
type MockCaseSource struct {
	ctrl     *gomock.Controller
	recorder *MockCaseSourceMockRecorder
	isgomock struct{}
}

// MockCaseSourceMockRecorder is the mock recorder for MockCaseSource.
type MockCaseSourceMockRecorder struct {
	mock *MockCaseSource
}

// NewMockCaseSource creates a new mock instance.
func NewMockCaseSource(ctrl *gomock.Controller) *MockCaseSource {
	mock := &MockCaseSource{ctrl: ctrl}
	mock.recorder = &MockCaseSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseSource) EXPECT() *MockCaseSourceMockRecorder {
	return m.recorder
}

// ReadDir mocks base method.
func (m *MockCaseSource) ReadDir(name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockCaseSourceMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockCaseSource)(nil).ReadDir), name)
}

// ReadFile mocks base method.
func (m *MockCaseSource) ReadFile(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockCaseSourceMockRecorder) ReadFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockCaseSource)(nil).ReadFile), name)
}

// MockHandler is a mock of Handler interface.
type MockHandler[C any] struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder[C]
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder[C any] struct {
	mock *MockHandler[C]
}

// NewMockHandler creates a new mock instance.
func NewMockHandler[C any](ctrl *gomock.Controller) *MockHandler[C] {
	mock := &MockHandler[C]{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder[C]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler[C]) EXPECT() *MockHandlerMockRecorder[C] {
	return m.recorder
}

// DecodeExpectedResponse mocks base method.
func (m *MockHandler[C]) DecodeExpectedResponse(raw json.RawMessage) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeExpectedResponse", raw)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeExpectedResponse indicates an expected call of DecodeExpectedResponse.
func (mr *MockHandlerMockRecorder[C]) DecodeExpectedResponse(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeExpectedResponse", reflect.TypeOf((*MockHandler[C])(nil).DecodeExpectedResponse), raw)
}

// DecodeRequest mocks base method.
func (m *MockHandler[C]) DecodeRequest(raw json.RawMessage) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeRequest", raw)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeRequest indicates an expected call of DecodeRequest.
func (mr *MockHandlerMockRecorder[C]) DecodeRequest(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeRequest", reflect.TypeOf((*MockHandler[C])(nil).DecodeRequest), raw)
}

// Invoke mocks base method.
func (m *MockHandler[C]) Invoke(ctx context.Context, client C, request any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", ctx, client, request)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockHandlerMockRecorder[C]) Invoke(ctx, client, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockHandler[C])(nil).Invoke), ctx, client, request)
}

// NormalizeResponse mocks base method.
func (m *MockHandler[C]) NormalizeResponse(response any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeResponse", response)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NormalizeResponse indicates an expected call of NormalizeResponse.
func (mr *MockHandlerMockRecorder[C]) NormalizeResponse(response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeResponse", reflect.TypeOf((*MockHandler[C])(nil).NormalizeResponse), response)
}

// MockHandlerRegistry is a mock of HandlerRegistry interface.
type MockHandlerRegistry[C any] struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerRegistryMockRecorder[C]
	isgomock struct{}
}

// MockHandlerRegistryMockRecorder is the mock recorder for MockHandlerRegistry.
type MockHandlerRegistryMockRecorder[C any] struct {
	mock *MockHandlerRegistry[C]
}

// NewMockHandlerRegistry creates a new mock instance.
func NewMockHandlerRegistry[C any](ctrl *gomock.Controller) *MockHandlerRegistry[C] {
	mock := &MockHandlerRegistry[C]{ctrl: ctrl}
	mock.recorder = &MockHandlerRegistryMockRecorder[C]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerRegistry[C]) EXPECT() *MockHandlerRegistryMockRecorder[C] {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockHandlerRegistry[C]) Resolve(name string) (Handler[C], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", name)
	ret0, _ := ret[0].(Handler[C])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockHandlerRegistryMockRecorder[C]) Resolve(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockHandlerRegistry[C])(nil).Resolve), name)
}

// Supported mocks base method.
func (m *MockHandlerRegistry[C]) Supported() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Supported")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Supported indicates an expected call of Supported.
func (mr *MockHandlerRegistryMockRecorder[C]) Supported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Supported", reflect.TypeOf((*MockHandlerRegistry[C])(nil).Supported))
}

// MockHarnessFactory is a mock of HarnessFactory interface.
type MockHarnessFactory[C any] struct {
	ctrl     *gomock.Controller
	recorder *MockHarnessFactoryMockRecorder[C]
	isgomock struct{}
}

// MockHarnessFactoryMockRecorder is the mock recorder for MockHarnessFactory.
type MockHarnessFactoryMockRecorder[C any] struct {
	mock *MockHarnessFactory[C]
}

// NewMockHarnessFactory creates a new mock instance.
func NewMockHarnessFactory[C any](ctrl *gomock.Controller) *MockHarnessFactory[C] {
	mock := &MockHarnessFactory[C]{ctrl: ctrl}
	mock.recorder = &MockHarnessFactoryMockRecorder[C]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHarnessFactory[C]) EXPECT() *MockHarnessFactoryMockRecorder[C] {
	return m.recorder
}

// New mocks base method.
func (m *MockHarnessFactory[C]) New(t *testing.T) C {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", t)
	ret0, _ := ret[0].(C)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockHarnessFactoryMockRecorder[C]) New(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockHarnessFactory[C])(nil).New), t)
}

// MockSuiteLifecycle is a mock of SuiteLifecycle interface.
type MockSuiteLifecycle[SC any] struct {
	ctrl     *gomock.Controller
	recorder *MockSuiteLifecycleMockRecorder[SC]
	isgomock struct{}
}

// MockSuiteLifecycleMockRecorder is the mock recorder for MockSuiteLifecycle.
type MockSuiteLifecycleMockRecorder[SC any] struct {
	mock *MockSuiteLifecycle[SC]
}

// NewMockSuiteLifecycle creates a new mock instance.
func NewMockSuiteLifecycle[SC any](ctrl *gomock.Controller) *MockSuiteLifecycle[SC] {
	mock := &MockSuiteLifecycle[SC]{ctrl: ctrl}
	mock.recorder = &MockSuiteLifecycleMockRecorder[SC]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuiteLifecycle[SC]) EXPECT() *MockSuiteLifecycleMockRecorder[SC] {
	return m.recorder
}

// SetupSuite mocks base method.
func (m *MockSuiteLifecycle[SC]) SetupSuite(t *testing.T) (SC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupSuite", t)
	ret0, _ := ret[0].(SC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupSuite indicates an expected call of SetupSuite.
func (mr *MockSuiteLifecycleMockRecorder[SC]) SetupSuite(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupSuite", reflect.TypeOf((*MockSuiteLifecycle[SC])(nil).SetupSuite), t)
}

// TeardownSuite mocks base method.
func (m *MockSuiteLifecycle[SC]) TeardownSuite(t *testing.T, suiteContext SC) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeardownSuite", t, suiteContext)
	ret0, _ := ret[0].(error)
	return ret0
}

// TeardownSuite indicates an expected call of TeardownSuite.
func (mr *MockSuiteLifecycleMockRecorder[SC]) TeardownSuite(t, suiteContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeardownSuite", reflect.TypeOf((*MockSuiteLifecycle[SC])(nil).TeardownSuite), t, suiteContext)
}

// MockSuiteCaseHarnessFactory is a mock of SuiteCaseHarnessFactory interface.
type MockSuiteCaseHarnessFactory[SC any, C any] struct {
	ctrl     *gomock.Controller
	recorder *MockSuiteCaseHarnessFactoryMockRecorder[SC, C]
	isgomock struct{}
}

// MockSuiteCaseHarnessFactoryMockRecorder is the mock recorder for MockSuiteCaseHarnessFactory.
type MockSuiteCaseHarnessFactoryMockRecorder[SC any, C any] struct {
	mock *MockSuiteCaseHarnessFactory[SC, C]
}

// NewMockSuiteCaseHarnessFactory creates a new mock instance.
func NewMockSuiteCaseHarnessFactory[SC any, C any](ctrl *gomock.Controller) *MockSuiteCaseHarnessFactory[SC, C] {
	mock := &MockSuiteCaseHarnessFactory[SC, C]{ctrl: ctrl}
	mock.recorder = &MockSuiteCaseHarnessFactoryMockRecorder[SC, C]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuiteCaseHarnessFactory[SC, C]) EXPECT() *MockSuiteCaseHarnessFactoryMockRecorder[SC, C] {
	return m.recorder
}

// NewCaseHarness mocks base method.
func (m *MockSuiteCaseHarnessFactory[SC, C]) NewCaseHarness(t *testing.T, suiteContext SC) C {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCaseHarness", t, suiteContext)
	ret0, _ := ret[0].(C)
	return ret0
}

// NewCaseHarness indicates an expected call of NewCaseHarness.
func (mr *MockSuiteCaseHarnessFactoryMockRecorder[SC, C]) NewCaseHarness(t, suiteContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCaseHarness", reflect.TypeOf((*MockSuiteCaseHarnessFactory[SC, C])(nil).NewCaseHarness), t, suiteContext)
}

// MockStatusCodec is a mock of StatusCodec interface.
type MockStatusCodec[S comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockStatusCodecMockRecorder[S]
	isgomock struct{}
}

// MockStatusCodecMockRecorder is the mock recorder for MockStatusCodec.
type MockStatusCodecMockRecorder[S comparable] struct {
	mock *MockStatusCodec[S]
}

// NewMockStatusCodec creates a new mock instance.
func NewMockStatusCodec[S comparable](ctrl *gomock.Controller) *MockStatusCodec[S] {
	mock := &MockStatusCodec[S]{ctrl: ctrl}
	mock.recorder = &MockStatusCodecMockRecorder[S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusCodec[S]) EXPECT() *MockStatusCodecMockRecorder[S] {
	return m.recorder
}

// Parse mocks base method.
func (m *MockStatusCodec[S]) Parse(raw string) (S, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", raw)
	ret0, _ := ret[0].(S)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockStatusCodecMockRecorder[S]) Parse(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockStatusCodec[S])(nil).Parse), raw)
}

// Success mocks base method.
func (m *MockStatusCodec[S]) Success() S {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Success")
	ret0, _ := ret[0].(S)
	return ret0
}

// Success indicates an expected call of Success.
func (mr *MockStatusCodecMockRecorder[S]) Success() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Success", reflect.TypeOf((*MockStatusCodec[S])(nil).Success))
}

// MockErrorInspector is a mock of ErrorInspector interface.
type MockErrorInspector[S comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockErrorInspectorMockRecorder[S]
	isgomock struct{}
}

// MockErrorInspectorMockRecorder is the mock recorder for MockErrorInspector.
type MockErrorInspectorMockRecorder[S comparable] struct {
	mock *MockErrorInspector[S]
}

// NewMockErrorInspector creates a new mock instance.
func NewMockErrorInspector[S comparable](ctrl *gomock.Controller) *MockErrorInspector[S] {
	mock := &MockErrorInspector[S]{ctrl: ctrl}
	mock.recorder = &MockErrorInspectorMockRecorder[S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorInspector[S]) EXPECT() *MockErrorInspectorMockRecorder[S] {
	return m.recorder
}

// FromError mocks base method.
func (m *MockErrorInspector[S]) FromError(err error) (S, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromError", err)
	ret0, _ := ret[0].(S)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// FromError indicates an expected call of FromError.
func (mr *MockErrorInspectorMockRecorder[S]) FromError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromError", reflect.TypeOf((*MockErrorInspector[S])(nil).FromError), err)
}
