// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=interfaces_mock.go -package=kafkaproducer
//

// Package kafkaproducer is a generated GoMock package.
package kafkaproducer

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockmessageWriter is a mock of messageWriter interface.
type MockmessageWriter struct {
	ctrl     *gomock.Controller
	recorder *MockmessageWriterMockRecorder
	isgomock struct{}
}

// MockmessageWriterMockRecorder is the mock recorder for MockmessageWriter.
type MockmessageWriterMockRecorder struct {
	mock *MockmessageWriter
}

// NewMockmessageWriter creates a new mock instance.
func NewMockmessageWriter(ctrl *gomock.Controller) *MockmessageWriter {
	mock := &MockmessageWriter{ctrl: ctrl}
	mock.recorder = &MockmessageWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageWriter) EXPECT() *MockmessageWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockmessageWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockmessageWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockmessageWriter)(nil).Close))
}

// WriteMessages mocks base method.
func (m *MockmessageWriter) WriteMessages(ctx context.Context, msgs ...harnessMessage) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockmessageWriterMockRecorder) WriteMessages(ctx any, msgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockmessageWriter)(nil).WriteMessages), varargs...)
}

// MockmessageReader is a mock of messageReader interface.
type MockmessageReader struct {
	ctrl     *gomock.Controller
	recorder *MockmessageReaderMockRecorder
	isgomock struct{}
}

// MockmessageReaderMockRecorder is the mock recorder for MockmessageReader.
type MockmessageReaderMockRecorder struct {
	mock *MockmessageReader
}

// NewMockmessageReader creates a new mock instance.
func NewMockmessageReader(ctrl *gomock.Controller) *MockmessageReader {
	mock := &MockmessageReader{ctrl: ctrl}
	mock.recorder = &MockmessageReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessageReader) EXPECT() *MockmessageReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockmessageReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockmessageReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockmessageReader)(nil).Close))
}

// FetchMessage mocks base method.
func (m *MockmessageReader) FetchMessage(ctx context.Context) (harnessMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMessage", ctx)
	ret0, _ := ret[0].(harnessMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMessage indicates an expected call of FetchMessage.
func (mr *MockmessageReaderMockRecorder) FetchMessage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMessage", reflect.TypeOf((*MockmessageReader)(nil).FetchMessage), ctx)
}
