// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mock.go -package=httpserver
//

// Package httpserver is a generated GoMock package.
package httpserver

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockhandlerProvider is a mock of handlerProvider interface.
type MockhandlerProvider struct {
	ctrl     *gomock.Controller
	recorder *MockhandlerProviderMockRecorder
	isgomock struct{}
}

// MockhandlerProviderMockRecorder is the mock recorder for MockhandlerProvider.
type MockhandlerProviderMockRecorder struct {
	mock *MockhandlerProvider
}

// NewMockhandlerProvider creates a new mock instance.
func NewMockhandlerProvider(ctrl *gomock.Controller) *MockhandlerProvider {
	mock := &MockhandlerProvider{ctrl: ctrl}
	mock.recorder = &MockhandlerProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhandlerProvider) EXPECT() *MockhandlerProviderMockRecorder {
	return m.recorder
}

// HTTPHandler mocks base method.
func (m *MockhandlerProvider) HTTPHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// HTTPHandler indicates an expected call of HTTPHandler.
func (mr *MockhandlerProviderMockRecorder) HTTPHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPHandler", reflect.TypeOf((*MockhandlerProvider)(nil).HTTPHandler))
}

// MockcookieJarProvider is a mock of cookieJarProvider interface.
type MockcookieJarProvider struct {
	ctrl     *gomock.Controller
	recorder *MockcookieJarProviderMockRecorder
	isgomock struct{}
}

// MockcookieJarProviderMockRecorder is the mock recorder for MockcookieJarProvider.
type MockcookieJarProviderMockRecorder struct {
	mock *MockcookieJarProvider
}

// NewMockcookieJarProvider creates a new mock instance.
func NewMockcookieJarProvider(ctrl *gomock.Controller) *MockcookieJarProvider {
	mock := &MockcookieJarProvider{ctrl: ctrl}
	mock.recorder = &MockcookieJarProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcookieJarProvider) EXPECT() *MockcookieJarProviderMockRecorder {
	return m.recorder
}

// HTTPCookieJar mocks base method.
func (m *MockcookieJarProvider) HTTPCookieJar() *CookieJar {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPCookieJar")
	ret0, _ := ret[0].(*CookieJar)
	return ret0
}

// HTTPCookieJar indicates an expected call of HTTPCookieJar.
func (mr *MockcookieJarProviderMockRecorder) HTTPCookieJar() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPCookieJar", reflect.TypeOf((*MockcookieJarProvider)(nil).HTTPCookieJar))
}

// MockBodyNormalizer is a mock of BodyNormalizer interface.
type MockBodyNormalizer struct {
	ctrl     *gomock.Controller
	recorder *MockBodyNormalizerMockRecorder
	isgomock struct{}
}

// MockBodyNormalizerMockRecorder is the mock recorder for MockBodyNormalizer.
type MockBodyNormalizerMockRecorder struct {
	mock *MockBodyNormalizer
}

// NewMockBodyNormalizer creates a new mock instance.
func NewMockBodyNormalizer(ctrl *gomock.Controller) *MockBodyNormalizer {
	mock := &MockBodyNormalizer{ctrl: ctrl}
	mock.recorder = &MockBodyNormalizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBodyNormalizer) EXPECT() *MockBodyNormalizerMockRecorder {
	return m.recorder
}

// NormalizeHTTPBody mocks base method.
func (m *MockBodyNormalizer) NormalizeHTTPBody(ctx BodyNormalizationContext) (any, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeHTTPBody", ctx)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NormalizeHTTPBody indicates an expected call of NormalizeHTTPBody.
func (mr *MockBodyNormalizerMockRecorder) NormalizeHTTPBody(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeHTTPBody", reflect.TypeOf((*MockBodyNormalizer)(nil).NormalizeHTTPBody), ctx)
}
